version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "develop"
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /
    target-branch: "develop"
    schedule:
      interval: weekly
