on:
  workflow_dispatch:
  push:
    branches:
      - main
      - k8s-deploy-stage
permissions:
  id-token: write
  contents: write
jobs:
  build-maven:
    name: Build Maven
    uses: ./.github/workflows/build-maven.yml
    with:
      version: 61.${{ github.run_number }}.${{ github.run_attempt }}
      java_version: 21
      java_distribution: "corretto"
  build-docker:
    name: Build Docker
    uses: ./.github/workflows/build-docker.yml
    with:
      version: 61.${{ github.run_number }}.${{ github.run_attempt }}
      image_name: "truemark/helloworld-java"
    secrets:
      aws_assume_role: ${{ secrets.AWS_ASSUME_ROLE }}
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    needs: [build-maven]
  deploy-stage:
    name: Deploy to Stage
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "stage"
      version: 61.${{ github.run_number }}.${{ github.run_attempt }}
    needs: [build-docker]
  deploy-prod:
    name: Deploy to Prod
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "prod"
    needs: [deploy-stage]

