on:
  workflow_call:
    secrets:
      docker_hub_username:
        description: "Docker Hub username"
        required: false
      docker_hub_password:
        description: "Docker Hub password"
        required: false
    inputs:
      image_name:
        description: "Name of the image"
        required: true
        type: string
      version:
        description: "Version of the project"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.docker_hub_username }}
      DOCKER_HUB_PASSWORD: ${{ secrets.docker_hub_password }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: env.DOCKER_HUB_USERNAME != '' && env.DOCKER_HUB_PASSWORD != ''
        with:
          username: ${DOCKER_HUB_USERNAME}
          password: ${DOCKER_HUB_PASSWORD}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            -f Dockerfile \
            -t ${{ inputs.image_name }}:${{ inputs.version }} \
            .
