on:
  workflow_call:
    inputs:
      major_version:
        description: "Major version of the project"
        required: false
        default: 1
        type: number
      java_version:
        description: "Java version to use"
        required: false
        default: 21
        type: number
      java_distribution:
        description: "Java distribution to use"
        required: false
        default: "corretto"
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: echo "VERSION=${{ inputs.major_version }}.${{ github.run_number }}.${{ github.run_attempt }}-SNAPSHOT" >> $GITHUB_ENV
      - name: Maven Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
      - name: Build Java
        run: ./mvnw -Drevision=${VERSION} package
