on:
  workflow_dispatch:
  push:
permissions:
  id-token: write
  contents: write
jobs:
  build-maven:
    name: Build Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: truemark/k8s-deployments
          ref: main
          path: k8s-deployments
