on:
  workflow_call:
#    secrets:
#      aws_assume_role:
#        description: "AWS role to assume"
#        required: false
#    inputs:
#      environment:
#        description: "Environment to deploy to"
#        required: true
#        type: string
jobs:
  deploy:
    # runs-on: public.ecr.aws/truemark/aws-cdk:ubuntu
    runs-on: truemark/aws-cdk:ubuntu
    steps:
      - uses: actions/checkout@v4

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          role-to-assume: "${{ secrets.aws_assume_role }}"
#          aws-region: "us-east-2"

      - name: CDK Deploy
        run: |
          cdk -c env=${{ inputs.environment }} diff
