on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Prepare Release
        run: |
          echo "Preparing release for environment ${{ inputs.environment }}"
          echo "Release version: ${{ github.run_number }}"
          echo "Release attempt: ${{ github.run_attempt }}"
          echo "Release environment: ${{ inputs.environment }}"
          echo "Release date: $(date)"

      - name: Update image tag in values.yaml
        run: |
          yq eval '.deployment.image.tag = "61.${{ github.run_number }}.${{ github.run_attempt }}"' -i values.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add values.yaml
          git commit -m "Update image tag for ${{ inputs.environment }} release"
          git push origin main

      - name: Force Update Tag
        run: |
          git tag -f ${GITHUB_REPOSITORY}-release-${{ inputs.environment }}
          git push origin --force ${GITHUB_REPOSITORY}-release-${{ inputs.environment }}

      - name: Create Release Tag for Run
        run: |
          git tag ${GITHUB_REPOSITORY}-release-${{ inputs.environment }}-${{ github.run_number }}-${{ github.run_attempt }}
          git push origin ${GITHUB_REPOSITORY}-release-${{ inputs.environment }}-${{ github.run_number }}-${{ github.run_attempt }}